namespace ModuleClient.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using ModuleClient.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<ModuleClient.Models.BddContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(ModuleClient.Models.BddContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
            context.Clients.AddOrUpdate(x => x.Id,
               new Client() { Id = 1, Prefixe = "M.", Nom = "SOLOFO RABONARIJAONA", Code = "SRAB", Solde = 5000, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 1, Nom = "COUZON", Prenom = "PIERRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 1, Adresse_1 = "46 Rue de la télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 2, Prefixe = "M.", Nom = "JOHN DOE", Code = "JDOE", Solde = 2500, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 2, Nom = "TOTO", Prenom = "PIERDFFDSFRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 2, Adresse_1 = "46 Rue de la télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 3, Prefixe = "M.", Nom = "BOB FISHER", Code = "BFISH", Solde = 1500, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 3, Nom = "TITI", Prenom = "PIEQSDFSDFSRRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 3, Adresse_1 = "46 Rue sqdfqsdf", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 4, Prefixe = "Mme", Nom = "LAYLA ALI", Code = "LALI", Solde = 500, Categorie = "Client", Etat = "Inactif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 4, Nom = "TATA", Prenom = "PISDQFSDFERRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 4, Adresse_1 = "46 Rue sqfsdfqsdf", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 5, Prefixe = "M.", Nom = "DAN BARON", Code = "DBAR", Solde = -250, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 5, Nom = "TOTO", Prenom = "PIESDFQSDRRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 5, Adresse_1 = "46 Rue sdqfsdf", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 6, Prefixe = "M.", Nom = "BILL GATES", Code = "BGAT", Solde = 8000, Categorie = "Prospect", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 6, Nom = "DTD", Prenom = "PIERSDQDFRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 6, Adresse_1 = "46 Rue de la télématisdqfsdfque", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 7, Prefixe = "M.", Nom = "STEVE JOBS", Code = "SJOB", Solde = 900, Categorie = "Client", Etat = "Inactif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 7, Nom = "DSSDQF", Prenom = "PISQDFSDERRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 7, Adresse_1 = "46 Rue de la télésqfsdfmatique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 8, Prefixe = "M.", Nom = "LINUS TORVALDS", Code = "LTOR", Solde = 7600, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 8, Nom = "SQDFSF", Prenom = "PIESFQSDFRRISDQFQSCK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 8, Adresse_1 = "46 Rue sqdfqsdfde la télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 9, Prefixe = "Mme", Nom = "JANE DIAS", Code = "JDIA", Solde = 2300, Categorie = "Prospect", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 9, Nom = "COUZQSDFSDFON", Prenom = "PIERRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 9, Adresse_1 = "46 Rue de la tsdfsqdfélématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 10, Prefixe = "M.", Nom = "RUDY ALLEN", Code = "RALL", Solde = -9000, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 10, Nom = "COUZDFON", Prenom = "PIERQSDFQSRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 10, Adresse_1 = "46 Rue de sqfsdfsdfla télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 11, Prefixe = "M.", Nom = "BRUCE WILLICE", Code = "BWIL", Solde = 7800, Categorie = "Client", Etat = "Inactif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 11, Nom = "CODSFDFUZON", Prenom = "PIEDFSFRRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 11, Adresse_1 = "46 Rue de sdqfsdfsdfla télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 12, Prefixe = "M.", Nom = "MARK ZUKERBERG", Code = "MZUK", Solde = 300, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 12, Nom = "COUZSDFSDFON", Prenom = "PIERRSDFQSDICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 12, Adresse_1 = "46 Rue de sqdfsdfsdfla télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 13, Prefixe = "Mme", Nom = "MICKAEL JORDAN", Code = "MJOR", Solde = 700, Categorie = "Prospect", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 13, Nom = "COUFSDSFZON", Prenom = "PIERRICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 13, Adresse_1 = "46 Rue de la tqsdfsdqfélématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 14, Prefixe = "M.", Nom = "JAMIE FOXX", Code = "JFOX", Solde = 9600, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 14, Nom = "SDFQSDFCOUZON", Prenom = "PIERRISSQDFSDCK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 14, Adresse_1 = "46 Rue de sqfsdfsdqfla télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } },
               new Client() { Id = 15, Prefixe = "M.", Nom = "KEVIN HART", Code = "KHAR", Solde = -4500, Categorie = "Client", Etat = "Actif", Mobile_1 = "06 02 03 04 05", Mobile_2 = "07 01 02 03 04", Tel = "01 02 03 04 05", Fax = "04 02 03 04 05", Email = "rabonarijaona@test.fr", Statut = "Particulier", Type = "Architecte", Interlocuteurs = new List<Interlocuteur>() { new Interlocuteur() { Id = 15, Nom = "COSDFQSDUZON", Prenom = "PIERRSQFSDFSDICK", Fonction = "Responsable de développement", Service = "Direction ESABORA", Telephone = "04 77 92 28 60" } }, AdresseDevis = new Adresse() { Id = 15, Adresse_1 = "46 Rue de lsqdfsdfa télématique", Adresse_2 = "Le Polygone", CodePostal = "42000", Ville = "St-Etienne", Pays = "France" } }
               );

        }
    }
}
